TypeError: undefined is not a function is the single most unhelpful error message in the history of error messages.  The thing was, I deliberately made an error to see if jasmine would help me catch it.
Jasmine did not help me catch it, because undefined is not afunction did not tell me where things were screwing up, what was undefined, or what function it was referring to.  So I couldn't use Jasmine to easily spot where things were going wrong o that I had a fighting chance o figure out what was going on.

Here's a hint: I left out a library that backbone depends on.  Specifically, backbone needs underscore to run properly.  Without it, a call like Backbone.Model.extend({}); doesn't work.  But also apparently you can't rely on jasmine to help you catch things like that.